export default {
  CHECK_ACCESS_TO_PAGE: 'CHECK_ACCESS_TO_PAGE',
  GET_S2S_DEFAULT_PARAMS: 'GET_S2S_DEFAULT_PARAMS',
  GET_S2S_DEFAULT_RECIPIENT: 'GET_S2S_DEFAULT_RECIPIENT',
  GET_L2F_DEFAULT_PARAMS: 'GET_L2F_DEFAULT_PARAMS',
};
