export default {
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_AUTH_PROCESS: 'SET_AUTH_PROCESS',
  SET_CLIENT_CRED: 'SET_CLIENT_CRED',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  LOAD_DOCUMENTS: 'LOAD_DOCUMENTS',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_DOCUMENTS: 'SET_TOTAL_DOCUMENTS',
  UPDATE_NAME: 'UPDATE_NAME',
};
