export default {
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_AUTH_PROCESS: 'SET_AUTH_PROCESS',
  SET_CLIENT_CRED: 'SET_CLIENT_CRED',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  LOAD_DOCUMENTS: 'LOAD_DOCUMENTS',
};
