export default {
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_AUTH_PROCESS: 'SET_AUTH_PROCESS',
  SET_CLIENT_CRED: 'SET_CLIENT_CRED',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  LOAD_DOCUMENTS: 'LOAD_DOCUMENTS',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_DOCUMENTS: 'SET_TOTAL_DOCUMENTS',
  SET_CURRENT_DOCUMENT: 'SET_CURRENT_DOCUMENT',
  RESET_CURRENT_DOCUMENT: 'RESET_CURRENT_DOCUMENT',
  SET_DOCUMENT_LINK: 'SET_DOCUMENT_LINK',
  RESET_DOCUMENT_LINK: 'RESET_DOCUMENT_LINK',
  UPDATE_NAME: 'UPDATE_NAME',
  SET_ERROR: 'SET_ERROR',
  RESET_ERROR: 'RESET_ERROR'
};
